### ISSUE TITLE
GCPLAYERGLOBALS.GLOBAL.MBIN doesn't decompile on 1.58.1

### ISSUE THREAD

**Issue by trevizor** [monkeyman192/MBINCompiler#74]
GCPLAYERGLOBALS.GLOBAL.MBIN doesn't decompile on 1.58.1

**Comment by Fuzzy-Logik** [comment]
Thank you.

This known, please check https://cdn.discordapp.com/attachments/289099380600864768/485156581986664458/CRC_changes_1.58_29aug18_-_1.58.1_31aug18.txt posted in [#mod-resources on discord](https://discord.gg/Dx2dfqU) for files that have been updated in the 1.58.1 release.

Please be patient when new NMS updates drop. No MBINCompiler update has been worked on for 1.58.1 yet.

**Comment by trevizor** [comment]
Yes, I know, sorry for making it look like I'm "demanding" an updated version.  :( 
Just wanted to make sure it was documented, since most of the files still work with older versions of Mbincompiler - even some present on the diff.

**Comment by monkeyman192** [comment]
Sorry, been a busy weekend. This is on the list for tonight!!

**Comment by wrentrillogy** [comment]
Yup after the update today can't decompile playerglobals aswell. Thanks again Monkeyman192 for making modding possible for us ;)

**Comment by monkeyman192** [comment]
yep, I have been informed!! I have extracted the data from the exe and will make a commit with the fixed global structs soon :)

**Comment by wrentrillogy** [comment]
Thank you :)

**Comment by wrentrillogy** [comment]
Just tried the new version says decompiled but gives me no xml?

**Comment by wrentrillogy** [comment]
Sweet thanks bro! Keep up the hard work take your time ;)

**Comment by GaticusHax** [comment]
@wrentrillogy Please file another bug report re: decompiled but no xml
That shouldn't be happening. An error should be reported on the screen.

**Comment by monkeyman192** [comment]
See if f5323ffce3c70272fac053c19c98810fb4539ca4 fixes the issue. If so I'll close this :)

**Comment by wrentrillogy** [comment]
There is no error it just simply doesn't not give the Xml for GCPLAYERGLOBALS.GLOBAL. At the bottom it says Decompiled but it doesnt. Re-downloaded closed reopened the compiler nothing seems to work with this one file. I can open anything else just trying to update my mods.

EDIT: I guess if it's just my end I can unpack the assets agin but did this after todays update for NMS!

**Comment by Catsbuggy** [comment]
[VERSION]: MBINCompiler v1.58.0.0
[ARGS]: "E:\SteamLibrary\steamapps\common\No Man's Sky\Tools\NMS Modding Station\Project\look official\GCPLAYERGLOBALS.GLOBAL.MBIN"

  If you encounter any errors, please submit a bug report and include this log file.
  Please check that there isn't already a similar issue open before creating a new one.
  https://github.com/monkeyman192/MBINCompiler/issues
  
[INFO]: Auto-Detected --input-format=MBIN


[ERROR]: [MbinException]: Failed serializing GcPlayerGlobals to EXML.
  [InvalidOperationException]: Erreur lors de la génération du document XML.
  [ArgumentException]: '', valeur hexadécimale 0x01, est un caractère non valide.

(personal edit :   [ArgumentException]: 'SOH', ....  on black backround in notepad+)

  [INFO]: E:\SteamLibrary\steamapps\common\No Man's Sky\Tools\NMS Modding Station\Project\look official\GCPLAYERGLOBALS.GLOBAL.MBIN
  [INFO]: MBIN	version:	0.0.0.0	guid:	A93A225F11D69DE6	template:	cGcPlayerGlobals
  
     à System.Xml.XmlEncodedRawTextWriter.InvalidXmlChar(Int32 ch, Char* pDst, Boolean entitize)
     à System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
     à System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
     à System.Xml.XmlEncodedRawTextWriterIndent.WriteString(String text)
     à System.Xml.XmlWellFormedWriter.WriteString(String text)
     à System.Xml.Serialization.XmlSerializationWriter.WriteAttribute(String localName, String ns, String value)
     à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write1_EXmlProperty(String n, String ns, EXmlProperty o, Boolean isNullable, Boolean needType)
     à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write5_EXmlData(String n, String ns, EXmlData o, Boolean isNullable, Boolean needType)
     à Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterEXmlData.Write6_Data(Object o)

i hope can help, else sorry

**Comment by GaticusHax** [comment]
Development for 1.58 is closed now.
This is fixed in the development branch for the next release v1.59.0-pre1

**Comment by wrentrillogy** [comment]
Closed but still cant decompile weird right? I even unpacked all assets again still says unpacked with no Xml. Could it be the mod station that needs updated? Again just really confused as I have never ran into this issue before!

**Comment by GaticusHax** [comment]
No further development will happen for NMS v1.58
NMS v1.59 is now public and GCPLAYERGLOBALS has changed again.
You will need to wait for the next 1.59 release of MBINCompiler this weekend.

**Comment by GaticusHax** [comment]
An interim version has been posted in the [#mod-mbin](https://discord.gg/xekBEJw) discord channel that has the GCPLAYERGLOBALS fix for v1.59
You can [download it here](https://cdn.discordapp.com/attachments/215569790801018880/487477516962103296/MBINCompiler-v1.59.0-pre0_dev.exe)

**Comment by wrentrillogy** [comment]
Thanks very much ;)

**Comment by wrentrillogy** [comment]
Get it unpacked but now it doesn't want to recompile back into MBIN lol idk. Guess i'll wait a week or so..
